@host = http://test.fhir.ch/r4

###
PUT {{host}}/Practitioner/AllzeitBereit HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/AllzeitBereit.xml

###
PUT {{host}}/Practitioner/HanspeterWengerByBFH HTTP/1.1
Content-Type: application/fhir+xml

< ./practitioner/HanspeterWengerByBFH.xml

###
PUT {{host}}/Person/SchreibKraft HTTP/1.1
Content-Type: application/fhir+xml

< ./person/SchreibKraft.xml


###
PUT {{host}}/Organization/GruppenpraxisCH HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/GruppenpraxisCH.xml

###
PUT {{host}}/Organization/Radiologieinstitut HTTP/1.1
Content-Type: application/fhir+xml

< ./organization/Radiologieinstitut.xml


###
PUT {{host}}/Patient/ElisabethBroennimannByBFH HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/ElisabethBroennimannByBFH.xml

###
PUT {{host}}/Patient/MaxMuster HTTP/1.1
Content-Type: application/fhir+xml

< ./patient/MaxMuster.xml


###
PUT {{host}}/Composition/ZuweisungZurRadiologischenDiagnostik HTTP/1.1
Content-Type: application/fhir+xml

< ./composition/ZuweisungZurRadiologischenDiagnostik.xml




###
GET {{host}}/Patient/ElisabethBroennimannByBFH HTTP/1.1
Content-Type: application/fhir+xml

###
GET {{host}}/Composition/ZuweisungZurRadiologischenDiagnostik/$document HTTP/1.1
Content-Type: application/fhir+xml
